# Generated by Django 4.2.6 on 2023-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('cooking_steps', models.TextField()),
                ('cooking_time', models.TimeField()),
                ('image', models.ImageField(upload_to='dishes_img/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
