# Generated by Django 4.2.6 on 2023-10-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
